### PR TITLE
[issue 76] optional Certificates for mTLS configuration

### PR DESCRIPTION
**Pull request by h0nIg**
# Description

This PR simply adds the possibility to support mTLS on top of TLS support, which is required to run rsyslog with a TLS endpoint over public ip address ranges.

The PR https://github.com/cloudfoundry/syslog-release/pull/77 introduces feature which supports a split configuration. @jochenehret and myself agreed that we can workaround this special case and will streamline the need for this split.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Testing performed?

- [ ] Unit tests
- [ ] Integration tests
- [ ] Acceptance tests

## Checklist:

- [x] This PR is being made against the `main` branch, or relevant version branch
- [x] I have made corresponding changes to the documentation
- [x] I have added testing for my changes

If you have any questions, or want to get attention for a PR or issue please reach out on the [#logging-and-metrics channel in the cloudfoundry slack](https://cloudfoundry.slack.com/archives/CUW93AF3M)

### CODE REVIEW

**Comment by h0nIg** [comment]
@Benjamintf1 may i ask for your review please?

**Comment by Benjamintf1** [comment]
Getting there.

could you make sure there's a test in https://github.com/cloudfoundry/syslog-release/blob/main/tests/acceptance_test.go and make sure it sets https://github.com/cloudfoundry/syslog-release/blob/23f3a341a50b4e466e9e76e0e8c3ab90d050eac6/jobs/syslog_storer/templates/rsyslog.conf.erb#L45 InputTCPServerStreamDriverAuthMode  on the storer such that it verifies that client tls is working?

**Comment by Benjamintf1** [comment]
hmm, btw, heads up, it looks like supporting bionic/jammy will require some changes to storer that, while minor, will effect this.

**Comment by h0nIg** [comment]
@Benjamintf1 done, may i ask you to review again and go ahead with the merge please?

**Review by Benjamintf1 — APPROVED** [review]
lgtm. Running tests.

**Comment by Benjamintf1** [comment]
Ty for your contribution!!

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry/syslog-release/releases/tag/v11.8.0

**Pull request merged**
