### PR TITLE
Ability to use Mutual TLS with syslog endpoints

### PR DESCRIPTION
**Pull request by 46bit**
Hi. This adds support for client certificates to the `syslog_forwarder` job, and adds relevant acceptance tests. See the commit message for details.

This feature was previously proposed in #36. We couldn't use their work because they didn't sign the CLA, but we took your advice around property naming onboard.

### CODE REVIEW

**Comment by anEXPer** [comment]
Nice work.

This team's not currently allocated any engineers. I'm caretaking. Regardless, I'll get some other eyeballs on it and we'll merge this, probably sometime next week.

**Comment by anEXPer** [comment]
I'm probably going to be making a syslog release soon, so I'm going through and attending to things to see what all we can get in the release.

"Probably sometime next week" is a phrase I should probably avoid using.

**Comment by 46bit** [comment]
@anEXPer That'd be awesome. But I should say that we don't rely on this feature anymore, so don't worry unduly about it :)

**Comment by vassi95** [comment]
Hi @anEXPer , Could you please take a look into the PR again? We would really take advantage of this feature and I could see that there is no update since July 2019. 
Is it possible to consider merging this PR and making a new release of the syslog forwarder? :)

**Comment by anEXPer** [comment]
A small number of merge conflicts have accumulated over the years, but nothing that looks problematic.

In short, this still looks good to me.

I'm not maintaining this release anymore personally, but there is a team associated with it now. I'll make sure this request comes to their attention.

**Pull request closed without merging**
