### PR TITLE
Expose send rebind config for use with load balancers.

### PR DESCRIPTION
**Pull request by jmcarp**
cc @wjwoodson @LinuxBozo

### CODE REVIEW

**Comment by anEXPer** [comment]
We're working on this now; we think we'll adjust the property names and descriptions, and see if we can't put some tests around this.

Also, since gitbot's post above, we've opened our tracker up, so the story should be visible now. Sorry about the private tracker - we're a new team, setup pangs.

**Comment by anEXPer** [comment]
@jmcarp why should the TCP and UDP rebind intervals be different? Is there a use case for having different values, here? Only one transport can actually be configured using the spec anyway.

Would there be anything wrong with a single `rebind_interval_msg_count` property that the template loads for both transports?

**Comment by jmcarp** [comment]
@anEXPer: did you want me to rename those properties or help with tests? Let me know if I can help move this along 😄

**Comment by anEXPer** [comment]
Thanks for the offer, @jmcarp.

We've got a satisfactory rename/merge of the properties. The thing this is blocked behind is a little more complicated and is something we don't really have a good way to accept help on.

Basically, a new team has taken over maintenance of this release. Right now, we're adding some test coverage, and are hesitant to take changes until we've figured out our test strategy and gotten acceptance tests working. Once we have an extensible acceptance test strategy, we'd be happy to take tests for this PR, so we may be in touch once we know how to accept testing help on this - though we also may find it useful to write such tests ourselves to validate that our approach works.

We're working on this right now, and this issue is right up at the top of the stack to be merged once we have a sensible and extensible acceptance testing approach for this release.

**Comment by mogul** [comment]
> We're working on this right now, and this issue is right up at the top of the stack to be merged once we have a sensible and extensible acceptance testing approach for this release.

Thanks for the update... Can you give us an idea what that means in real time... Days, weeks, months?

**Comment by mogul** [comment]
Pinging again now that the holiday season's past us...
> Can you give us an idea what that means in real time... Days, weeks, months?

**Comment by anEXPer** [comment]
Thanks for the followup.

I avoid time-based estimates, because they are very rarely anything but wrong. (For instance, I considered some non-committal version of "I bet it won't be longer than a month before we can get to this" in answer to your previous comment. Wrong.) But I'm able to provide an update, and a more qualitative estimate.

We've got an acceptance testing approach figured out enough to get a mitigation for an issue (https://github.com/cloudfoundry/syslog-release/issues/34) out.

Extending those tests to account for this feature should be relatively straightforward. The hardest part seems likely to be instrumenting the receiving side so as to be able to assert that connections have been properly reset. If y'all would like to try your hand at it, it might make getting this merged a smaller bite for us to break off. This is a factor, because syslog PRs aren't as high a staffing priority as might be ideal. Something else for us to work on, eh?

I think we've got the changes we were thinking of making to the interface stashed somewhere. I'll try to get them pushed today; then it will just be a matter of getting time to write or understand tests and get this merged.

Oh, also, this PR should be against `develop`, not `master`.

Thanks!

**Comment by anEXPer** [comment]
@jmcarp we'll be happy to merge this when:
- the two properties are merged as I'd suggested before
- there are Ginkgo tests for this new feature

We've actually got a reasonable testing framework now, please feel free to ask if you'd like a walkthrough, or swing by the #syslog channel in the cloudfoundry slack.

**Comment by jmcarp** [comment]
@anEXPer: what would you expect the tests to look like? We could configure the reconnection count to some value and assert that rsyslog reconnects after sending exactly that number of messages. But that would effectively be re-testing a behavior that's already covered by the rsyslog unit tests, so I'm not sure what value it would add.

**Comment by anEXPer** [comment]
If, by reformatting the config files at some point in the future, I cause this feature to stop working, I would like to know.

It's not unit test coverage, it's acceptance test coverage. The test you describe undoubtedly treads the same ground as a variety of tests for rsyslog, bosh, and linux - but the end-to-end functioning of this feature isn't covered, and that's what we'd like to see.

At some point I'd like to unit test the rendering of the spec into the templates, and that the resulting .conf files checkout okay from rsyslog's point of view. We don't have a framework for that kind of test right now, which is too bad, because that's the sort of smaller-scale test that would be well-suited to help avoid accidentally breaking features we don't use.

If you feel strongly that an end-to-end acceptance test deploying with this property configured and then observing the desired behavior is overkill, I'd be open to that argument. Just because we have one type of testing automation figured out doesn't mean we should be doing everything at that level, and just because the appropriate level of testing isn't figured out yet doesn't mean we can't accept PRs at all. We can take some things without tests; it's no worse than the status quo before we started adding test coverage.

We're just a little jumpy about it, and it's an ongoing conversation.

**Comment by anEXPer** [comment]
We're happy to continue this conversation, but there's been no activity on over a month, so we're closing this for now. Please feel free to open something like this again.

**Comment by jmcarp** [comment]
Thanks for the reminder--I forgot about this 😅. I'm happy to write an integration test for this, but not sure where to start. The existing tests look pretty straightforward, but to test this behavior, I'd need to add more tooling to watch for reconnects, then make assertions about them after some number of logs. Any tips much appreciated.

**Comment by anEXPer** [comment]
Yeah, when we were batting around the idea of just writing the tests ourselves, we came up against the same question.

There might be logs from rsyslog itself on the storer side to indicate reconnects; if so, they'd be easy to look for. We've not validated that such a thing exists.

You could also go full integration test on this, add an HA proxy and a second storer to the manifest, and look to see that, when the send rebind is set to one message and you've sent, say, ten, that you can see test messages on both storers. This has the virtue of illustrating the intended behavior, rather than just testing an implementation detail.

**Comment by anEXPer** [comment]
(Also we went ahead and re-opened this. Feel free to close it if you'd prefer to start fresh or whatever, but we figured this would be more convenient, given you're still interested.)

**Comment by Benjamintf1** [comment]
Hey @jmcarp are you still interested in this?

**Comment by anEXPer** [comment]
We're probably going to close this again soon.

**Pull request closed without merging**
