### PR TITLE
Allow client certs to be configurable

### PR DESCRIPTION
**Pull request by jccarte**
Our syslog endpoint requires a client cert. This PR adds optional client cert/key properties.

### CODE REVIEW

**Comment by anEXPer** [comment]
Hello @jccarte, and thanks for the PR. Sorry it's taken us a little bit to get to it.

First things first, I've changed your PR to be against `develop` rather than master. Unfortunately, this leads to a merge conflict; it should be simple to resolve; we've moved the `rsyslog.conf.erb` template to `syslog-release.conf.erb` in the same directory.

We'll change the default branch in github so it's easier for others to avoid this misstep in the future.

Secondly, we now have an integration testing suite in `tests/acceptance_test.go`.

We're trying to avoid adding substantive new features without tests. Would you be willing to contribute an acceptance test for this new feature? We'd be available to discuss testing strategy or even perhaps pair on implementation.

**Comment by cppforlife** [comment]
i think it would be great if we converge toward following configuration for tls: http://bosh.io/docs/props-common.html#tls

**Comment by anEXPer** [comment]
I (think I) agree with @cppforlife. I'd like to see these two properties nested under `syslog.client_tls.cert` and `syslog.client_tls.key`. (I mean, I'd rather get rid of the `syslog` at the beginning, but it's probably not time to start de-globalizing our spec's paths just yet.) This would help to clarify their purpose as client certs, and group the cert and key properties together such that they can be easily consumed from the data structures BOSH uses to store certs in config servers and vars stores.

Also, I'd like you to add a `syslog.client_tls.enabled` property. The linked doc indicates the default should be true, but I'm not sure that's right in this case. TLS defaulting to true makes sense for a lot of jobs doing mutual TLS or terminating HTTPS requests; I'm not (yet) convinced it makes sense for TLS client certs. My understanding is that outgoing logs are more typically encrypted using the drain's server cert, so using client certs should probably be `false` by default.

@cppforlife, would that make sense from your perspective?

@jccarte, this discussion also leads me to believe a more extensive spec description would be useful. "Client cert if required" doesn't actually tell me what kind of system would require this or why it would be useful. The new `syslog.client_tls.enabled` property provides an opportunity to more comprehensively describe what is being enabled and why someone would want it without cluttering up the descriptions of the cert and key properties.

**Comment by jccarte** [comment]
Yeah, i agree defaulting to false and the properties changes makes sense . I can add some additional description as well. In my case it is purely because our syslog server requires a client cert due to our security policies and its configuration.

**Comment by Benjamintf1** [comment]
We're still open to this (or a similar) PR, with the above-discussed changes. However, it's been a few months with no activity, so we're closing for now.

**Pull request closed without merging**
