### PR TITLE
switch from gnutls to openssl

### PR DESCRIPTION
**Pull request by h0nIg**
# Description

see https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/249#issuecomment-1301858805, especially https://github.com/rsyslog/rsyslog/issues/3915

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing performed?

- [x] Unit tests
- [ ] Integration tests
- [ ] Acceptance tests

## Checklist:

- [x] This PR is being made against the `main` branch, or relevant version branch
- [ ] I have made corresponding changes to the documentation
- [ ] I have added testing for my changes

If you have any questions, or want to get attention for a PR or issue please reach out on the [#logging-and-metrics channel in the cloudfoundry slack](https://cloudfoundry.slack.com/archives/CUW93AF3M)

### CODE REVIEW

**Comment by Benjamintf1** [comment]
Could you please add a test case for relp to this pr

**Review by Benjamintf1 — APPROVED** [review]
Checking against existing behavior in ci.

**Comment by Benjamintf1** [comment]
Yup, you broke tls.

**Comment by Benjamintf1** [comment]
image

**Comment by rkoster** [comment]
@Benjamintf1 could it be that the above failure is because this PR: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/254 has not been merged yet (as in the required package is not yet installed on the stemcell)? 

From your perspective are you okay with the above PR being merged? Or do you want to perform additional validation before the stemcell change is made?

**Comment by Benjamintf1** [comment]
I'll try and look into this a little more today. In the meantime I'll try and also get a test up. https://github.com/cloudfoundry/syslog-release/pull/103. 

My recollection is I got errors that said `x isn't a good parameter` or `x is required when using tls` or something like that in my syslog logs when I used tls and ossl last time(when trying to figure out jammy bugs), but I havn't looked since.

It'd make sense that we need the package, but I havn't looked into it in more depth at the moment.

**Comment by Benjamintf1** [comment]
image
Here's a set of example logs when tls is enabled on relp after I installed the package ossl.

**Comment by Benjamintf1** [comment]
https://github.com/rsyslog/rsyslog/issues/3413 Here's this if I havn't linked it for *some* context btw.

**Comment by Benjamintf1** [comment]
@rkoster Do we know what got the rsyslog-ossl package removed from jammy? (is it something that's on bionic and xenial right now?). 

Having the "om relp is configured" on the stemcell config(not the package but the rsyslog config) seems a bit weird to me? Especially saying "and it uses ossl", seems like it has much more of a home in syslog release? 

It seems like *maybe* the only problems I ran into, on jammy, and using relp was that 1) had to install the ossl package and 2) had to get the certificates to have server-purpose(😨 ). Which if that's the outcome, seems not so scary from a universal standpoint(?). I don't see why we would need to special case relp tho for the ossl changes.

**Comment by rkoster** [comment]
Bionic and Xenial both don't have `rsyslog-ossl`: 
- Jammy: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu-jammy/master/bosh-stemcell/spec/assets/dpkg-list-ubuntu-jammy.txt
- Xenial: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu-xenial/621.x/bosh-stemcell/spec/assets/dpkg-list-ubuntu-xenial.txt

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry/syslog-release/pull/105 This shouldn't require waiting for the stemcell to work.

**Comment by Benjamintf1** [comment]
Library is now settable with `syslog.tls_library`.

**Pull request closed without merging**
