### PR TITLE
Migrate stop of rsyslogd to post-stop

### PR DESCRIPTION
**Pull request by KarstenSchnitter**
# Description

Moves the stopping of rsyslogd to post-stop phase, so that logs during stopping of bosh jobs are still forwarded to the configured syslog target.
This addresses https://github.com/cloudfoundry/syslog-release/issues/131.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing performed?

- [ ] Unit tests
- [ ] Integration tests
- [ ] Acceptance tests

## Checklist:

- [x] This PR is being made against the `main` branch, or relevant version branch
- [ ] I have made corresponding changes to the documentation
- [ ] I have added testing for my changes

### CODE REVIEW

**Comment by ctlong** [comment]
@KarstenSchnitter looks like you're going to have to sign the CLA to proceed

**Comment by KarstenSchnitter** [comment]
@ctlong signing the CLA has been done.

**Review by Benjamintf1 — APPROVED** [review]
lgtm

**Review by mkocher — APPROVED** [review]
seems like a good change to me! Thanks @KarstenSchnitter

**Comment by maxmoehl** [comment]
Thank you all! Do you have an ETA on a new release with this fix?

**Comment by ctlong** [comment]
We just cut a patch release!

**Pull request merged**
