### PR TITLE
added drain script for rsyslog

### PR DESCRIPTION
**Pull request by tracyde**
This fixes the issue where bosh fails to update because /var/vcap/store is unable to be un-mounted.

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
Initiated by some related discussion [in slack](https://cloudfoundry.slack.com/archives/bosh/p1462904507001597).

**Comment by tracyde** [comment]
I submitted my CLA and made the Pivotal orgs I am a member of public.

**Comment by cppforlife** [comment]
@tracyde correct me if im wrong but i dont think rsyslog open any files on persistent disk.

**Comment by tracyde** [comment]
@cppforlife the `syslog_storer` job in the release does setup rsyslog to store files on `/var/vcap/store`

**Comment by anEXPer** [comment]
We've since resolved this issue, which we'd run into ourselves. There's a new team maintaining this, and we didn't see that you'd already done the work for us.

So, thank you for the PR, sorry we didn't merge it, we wish we'd noticed it before duplicating your work.

**Pull request closed without merging**
